runtime: python38
env: standard
entrypoint: gunicorn -b :$PORT PTCG2win.wsgi
instance_class: F2
handlers:
  - url: /static/(.*)
    static_files: static/\1
    require_matching_file: false
    upload: static/.*
  - url: /.*
    script: auto
  - url: .*
    script: auto
automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 5
  min_pending_latency: 3000ms
  max_pending_latency: automatic