# Generated by Django 2.0.5 on 2018-05-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.CharField(default='Not set', max_length=10000),
        ),
    ]
