# Generated by Django 2.1.1 on 2018-09-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=10)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.Type')),
            ],
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weakness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='decks.Weakness'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='resistance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='decks.Resistance'),
        ),
    ]
