# Generated by Django 2.0.5 on 2018-05-17 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_comments_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='Comment text is not set.', max_length=10000),
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='Title is not set.', max_length=150),
        ),
        migrations.AlterField(
            model_name='archtype',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='decks.Regulation'),
        ),
    ]
