# Generated by Django 2.0.5 on 2018-05-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_auto_20180518_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.Card')),
            ],
        ),
        migrations.AlterField(
            model_name='decklist',
            name='cards',
            field=models.ManyToManyField(blank=True, to='decks.CardBundle'),
        ),
    ]
