# Generated by Django 2.0.5 on 2018-05-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_auto_20180519_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decklist',
            old_name='cards',
            new_name='card_bundles',
        ),
    ]
