# Generated by Django 2.0.5 on 2018-05-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_auto_20180519_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbundle',
            name='deck_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.DeckList'),
        ),
    ]
